server:
  port: 8080

spring:
#  console color
  output:
    ansi:
      enabled: ALWAYS
#  DataBase Connect
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_jwt?serverTimezone=Asia/Seoul&characterEncoding=utf8&autoReconnection=true
    username: seung
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  JPA 설정
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#      use-new-id-generator-mappings: false

#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
